"""Created Chef Model

Revision ID: ed4ac43729ef
Revises: 9b051368d239
Create Date: 2025-04-16 15:35:53.380623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4ac43729ef'
down_revision: Union[str, None] = '9b051368d239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('chef_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['chefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chefs')
    # ### end Alembic commands ###
