# Generated by Django 5.0.4 on 2025-03-06 15:42

import main_app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_veterinarian_zookeeper'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooDisplayAnimal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.animal',),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='availability',
            field=main_app.fields.BooleanChoiceField(choices=[(True, 'Available'), (False, 'Not Available')], default=True),
        ),
    ]
