# Generated by Django 5.2.1 on 2025-07-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('approve_post', 'Can approve post')]},
        ),
    ]
